puphpet.vagrantfile_gce.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:VagrantfileGce:index }

puphpet.vagrantfile_gce.machine:
    path: /machine
    defaults: { _controller: PuphpetBundle:VagrantfileGce:machine }

puphpet.vagrantfile_gce.synced_folder:
    path: /synced-folder
    defaults: { _controller: PuphpetBundle:VagrantfileGce:syncedFolder }
