puphpet.postgresql.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:PostgreSql:index }

puphpet.postgresql.add_user:
    path:  /add-user
    defaults: { _controller: PuphpetBundle:PostgreSql:addUser }

puphpet.postgresql.add_database:
    path:  /add-database
    defaults: { _controller: PuphpetBundle:PostgreSql:addDatabase }

puphpet.postgresql.add_grant:
    path:  /add-grant
    defaults: { _controller: PuphpetBundle:PostgreSql:addGrant }
