puphpet.mariadb.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:MariaDb:index }

puphpet.mariadb.add_user:
    path:  /add-user
    defaults: { _controller: PuphpetBundle:MariaDb:addUser }

puphpet.mariadb.add_database:
    path:  /add-database
    defaults: { _controller: PuphpetBundle:MariaDb:addDatabase }

puphpet.mariadb.add_grant:
    path:  /add-grant
    defaults: { _controller: PuphpetBundle:MariaDb:addGrant }
