puphpet.vagrantfile_aws.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:VagrantfileAws:index }

puphpet.vagrantfile_aws.machine:
    path: /machine
    defaults: { _controller: PuphpetBundle:VagrantfileAws:machine }

puphpet.vagrantfile_aws.synced_folder:
    path: /synced-folder
    defaults: { _controller: PuphpetBundle:VagrantfileAws:syncedFolder }
