versions:
    - 8.0.5
    - 8.0.4
    - 8.0.3
    - 8.0.2
    - 8.0.1
    - 8.0.0
    - 7.1.0
    - 7.0.0
    - 6.7.0
    - 6.6.0
    - 6.5.0
    - 6.4.0
    - 6.3.0
    - 6.2.0
    - 6.1.0
    - 6.0.0
