puphpet.vagrantfile_rackspace.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:VagrantfileRackspace:index }

puphpet.vagrantfile_rackspace.machine:
    path: /machine
    defaults: { _controller: PuphpetBundle:VagrantfileRackspace:machine }

puphpet.vagrantfile_rackspace.synced_folder:
    path: /synced-folder
    defaults: { _controller: PuphpetBundle:VagrantfileRackspace:syncedFolder }
