puphpet.mysql.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:Mysql:index }

puphpet.mysql.add_user:
    path:  /add-user
    defaults: { _controller: PuphpetBundle:Mysql:addUser }

puphpet.mysql.add_database:
    path:  /add-database
    defaults: { _controller: PuphpetBundle:Mysql:addDatabase }

puphpet.mysql.add_grant:
    path:  /add-grant
    defaults: { _controller: PuphpetBundle:Mysql:addGrant }
