puphpet.vagrantfile_linode.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:VagrantfileLinode:index }

puphpet.vagrantfile_linode.machine:
    path: /machine
    defaults: { _controller: PuphpetBundle:VagrantfileLinode:machine }

puphpet.vagrantfile_linode.synced_folder:
    path: /synced-folder
    defaults: { _controller: PuphpetBundle:VagrantfileLinode:syncedFolder }
