puphpet.vagrantfile_softlayer.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:VagrantfileSoftlayer:index }

puphpet.vagrantfile_softlayer.machine:
    path: /machine
    defaults: { _controller: PuphpetBundle:VagrantfileSoftlayer:machine }

puphpet.vagrantfile_softlayer.synced_folder:
    path: /synced-folder
    defaults: { _controller: PuphpetBundle:VagrantfileSoftlayer:syncedFolder }
