puphpet.vagrantfile_digitalocean.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:VagrantfileDigitalOcean:index }

puphpet.vagrantfile_digitalocean.machine:
    path: /machine
    defaults: { _controller: PuphpetBundle:VagrantfileDigitalOcean:machine }

puphpet.vagrantfile_digitalocean.synced_folder:
    path: /synced-folder
    defaults: { _controller: PuphpetBundle:VagrantfileDigitalOcean:syncedFolder }
