puphpet.apache.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:Apache:index }

puphpet.apache.vhost:
    path:  /vhost
    defaults: { _controller: PuphpetBundle:Apache:vhost }

puphpet.apache.directory:
    path:  /directory
    defaults: { _controller: PuphpetBundle:Apache:directory }

puphpet.apache.files_match:
    path:  /files-match
    defaults: { _controller: PuphpetBundle:Apache:filesMatch }
