puphpet.vagrantfile_local.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:VagrantfileLocal:index }

puphpet.vagrantfile_local.machine:
    path: /machine
    defaults: { _controller: PuphpetBundle:VagrantfileLocal:machine }

puphpet.vagrantfile_local.machine_forwarded_port:
    path: /machine-forwarded-port/{mId}
    defaults: { _controller: PuphpetBundle:VagrantfileLocal:machineForwardedPort }

puphpet.vagrantfile_local.synced_folder:
    path: /synced-folder
    defaults: { _controller: PuphpetBundle:VagrantfileLocal:syncedFolder }
