puphpet.python.homepage:
    path:     /
    defaults: { _controller: PuphpetBundle:Python:index }

puphpet.python.add_version:
    path:  /add-version
    defaults: { _controller: PuphpetBundle:Python:addVersion }
