puphpet.rabbitmq.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:RabbitMq:index }

puphpet.rabbitmq.user:
    path:  /user
    defaults: { _controller: PuphpetBundle:RabbitMq:user }

puphpet.rabbitmq.permission:
    path:  /permission/{userId}
    defaults: { _controller: PuphpetBundle:RabbitMq:permission }
